language: c

env:
  matrix:
    - R_PKG="$(basename $TRAVIS_REPO_SLUG)"
  global:
    secure: UTJJhiel0TE8NgLhE9lLtXcZiqWT7y2UObDZ8aAU1ZFiL9S4u/MTDU9Ea3pOGgzSWE1aUU7lquVjtf1funLpEwHyRXWHCfee+1e37AE7EN+gC7QclHoL6S7L2lIf0srMOiDkANyei342qoF7iYDXjDac1bfBlvk0z5kN3Qmcz/8=

install:
  - sudo apt-add-repository -y "deb http://cran.rstudio.com/bin/linux/ubuntu `lsb_release -cs`/"
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
  - sudo apt-add-repository -y ppa:marutter/c2d4u
  - sudo apt-get update
  - sudo apt-get install r-base-dev r-cran-httpuv r-cran-devtools
  - "wget -q -O - http://yihui.name/xran/r-config | bash"
  - "[ ! -d ~/bin ] && mkdir ~/bin"
  - "export PATH=$PATH:$HOME/bin"
  - "wget -q -O - https://github.com/yihui/crandalf/raw/master/inst/scripts/install-pandoc | bash"
  - Rscript -e "devtools::install_deps(dep = TRUE)"

script:
  - cd ..; rm -f *.tar.gz; R CMD build $R_PKG
  - R CMD check ${R_PKG}_*.tar.gz --no-manual
  - cd $R_PKG

# deploy to XRAN
after_success:
  - set -e
  - "(wget -q -O - http://yihui.name/xran/r-xran | bash)"

after_failure:
  - cd ..; for i in `ls *.Rcheck/00*`; do cat $i; done
